# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5ae09081fa7ef25b3af46118976582cd60a77a2bfeaebfe28cec7b0ee114c7c38933f7bfca02eb021a155c46437b66e7d3a417cdb728a09738aae66c787de29

test:
  secret_key_base: 87ca38a13434c88aa9205ef6a856a0a0f4706f25a9184c2a3173438103a0cc4bf2cd1a5d24ecf36a0d7bef356825aeffbad1da4123b29c1704df7334b8cfe365

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
